# Generated by Django 3.1.6 on 2021-03-14 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeaBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='블로그 제목')),
                ('is_public', models.CharField(choices=[('PUB', 'Public'), ('PRV', 'Private')], default='PUB', max_length=3, verbose_name='공개 상태')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='개최자')),
            ],
        ),
        migrations.CreateModel(
            name='TeaPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('post_title', models.CharField(max_length=500, verbose_name='포스트 제목')),
                ('post_body', models.TextField(verbose_name='글')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.teablog', verbose_name='블로그')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(verbose_name='댓글')),
                ('hanged_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.teapost', verbose_name='달린 포스트')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='댓글쓴이')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
