# Generated by Django 3.1.6 on 2021-03-18 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '댓글', 'verbose_name_plural': '댓글'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comment_body',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='hanged_post',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='teapost',
            name='blog',
        ),
        migrations.AddField(
            model_name='teapost',
            name='posted_blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.teablog', verbose_name='포스트된 블로그'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='댓쓴이'),
        ),
        migrations.AlterField(
            model_name='teablog',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='teapost',
            name='post_body',
            field=models.TextField(),
        ),
    ]
